// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMexIxotV1P5kjiBSr5uZ9EGHdy1dvAog',
    appId: '1:1073156168381:web:464b02f5ee54e774fdf5d4',
    messagingSenderId: '1073156168381',
    projectId: 'chatone-234bd',
    authDomain: 'chatone-234bd.firebaseapp.com',
    storageBucket: 'chatone-234bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCln36ImTTl-jJKx10LBx3J4EYZeKX_AMk',
    appId: '1:1073156168381:android:dafb6ad5cda0cc71fdf5d4',
    messagingSenderId: '1073156168381',
    projectId: 'chatone-234bd',
    storageBucket: 'chatone-234bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefpeId4hhFQ3Gjx76ot3p21YZyrn6lVI',
    appId: '1:1073156168381:ios:661cc6175db84648fdf5d4',
    messagingSenderId: '1073156168381',
    projectId: 'chatone-234bd',
    storageBucket: 'chatone-234bd.appspot.com',
    iosClientId: '1073156168381-irmdu1cv3985b1r3vvuog9ut3f3cauoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.onechat',
  );
}
